<h1>Skills</h1>
<ul>

{/* <// <-----------------------> */}
<li>JS</li>
{/* // <--------https://cdn.clipart.email/e495e39faa9fa3d038bb7bdc166562fa_javascript-comment-html-logo-international-conference-on-missions-_728-1023.jpeg--------------------> */}

<li>React</li>
{/* // <----------https://img.pngio.com/10-years-of-experience-react-native-logo-svg-hd-png-download-react-png-840_817.png------------------> */}
<li>Html</li>

{/* // <---------------https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/512px-HTML5_logo_and_wordmark.svg.png-------------> */}
 
<li>CSS</li>

{/* // <---------https://www.freepnglogos.com/uploads/html5-logo-png/html5-logo-opencode-css-8.png-------------------> */}

<li>Python</li>
{/* // <----------------------------> */}

<li>Rest/li>

<li>Django</li>

<li>Flask</li>
{/* // <----------------------------> */}

<li>MySQL</li>

<li>SqlAlchemy</li>
{/* // <----------------------------> */}
</ul>
// <------------------------->
// ###########here we are going to add all skills###########################
// ############### adding pictures and icons may add bootstrap################
