<h1>Skills</h1>
<ul>

{/* <// <-----------------------> */}
<li>JS</li>
{/* // <--------https://cdn.clipart.email/e495e39faa9fa3d038bb7bdc166562fa_javascript-comment-html-logo-international-conference-on-missions-_728-1023.jpeg--------------------> */}

<li>React</li>
{/* // <----------------------------> */}
<li>Html</li>

{/* // <----------------------------> */}
 
<li>CSS</li>

{/* // <----------------------------> */}

<li>Python</li>
{/* // <----------------------------> */}

<li>Rest/li>

<li>Django</li>

<li>Flask</li>
{/* // <----------------------------> */}

<li>MySQL</li>

<li>SqlAlchemy</li>
{/* // <----------------------------> */}
</ul>
// <------------------------->
// ###########here we are going to add all skills###########################
// ############### adding pictures and icons may add bootstrap################
