<h1>Skills</h1>
<ul>

{/* <// <-----------------------> */}
<li>JS</li>
{/* // <--------https://cdn.clipart.email/e495e39faa9fa3d038bb7bdc166562fa_javascript-comment-html-logo-international-conference-on-missions-_728-1023.jpeg--------------------> */}

<li>React</li>
{/* // <----------https://img.pngio.com/10-years-of-experience-react-native-logo-svg-hd-png-download-react-png-840_817.png------------------> */}
<li>Html</li>

{/* // <---------------https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/512px-HTML5_logo_and_wordmark.svg.png-------------> */}
 
<li>CSS</li>

{/* // <---------https://www.freepnglogos.com/uploads/html5-logo-png/html5-logo-opencode-css-8.png-------------------> */}

<li>Python</li>
{/* // <-------------https://lh3.googleusercontent.com/proxy/Neh3_17ZMQZ_6ZUb-znYjRoUXRIsPNy-YEOdAamdZcpcMA6-nNW2OnhO3tsANPaM3xKR8QR9c_sWTbIFI4xCqicbYuKUbuUHjBR0Owc2mYTsYtufti3TIwXwf7MYycdNmyI---------------> */}

<li>Rest/li>
{/* <// <-------------https://www.ardoq.com/hubfs/TP%20Theme/Website/Integrations/restApi.png----------> */}
<li>Django</li>
{/* // <----------https://img.favpng.com/20/6/19/django-python-computer-icons-logo-portable-network-graphics-png-favpng-fmTDmunynSK52axsEWGWJeDad.jpg------------------> */}
<li>Flask</li>
{/* <// <--------------https://banner2.cleanpng.com/20180809/hvf/kisspng-flask-by-example-web-framework-python-bottle-sebastian-estenssoro-5b6c0aa33b3b57.9170119715338072672426.jpg---------> */}

<li>MySQL</li>
{/* <// <---------https://banner2.cleanpng.com/20180803/bkf/kisspng-logo-mysql-database-phpmyadmin-mysql-digital-agency-maidenhead-web-agency-uk-5b6475c3513438.3209368415333104033326.jpg--------------> */}
<li>SqlAlchemy</li>
{/* // <----------------https://marshmallow-sqlalchemy.readthedocs.io/en/latest/_static/marshmallow-sqlalchemy-logo.png------------> */}
<li>Agile/Scrum</li>
{/* <// <------------https://img.favpng.com/19/19/5/scrum-agile-software-development-project-sprint-requirement-png-favpng-PY3ygK6e89sBERhbGGCe3u4N2.jpg-----------> */}


</ul>
// <------------------------->
// ###########here we are going to add all skills###########################
// ############### adding pictures and icons may add bootstrap################
